### ISSUE TITLE
Compatibility React 18

### ISSUE THREAD

**Issue by alxbrla** [nocturneio/react-dpe-generator#1]
I use this component with the latest version on nextjs wich uses the last version of React, but the component is not compatible with React 18, will you update it ?

**Comment by cldt-fr** [comment]
Done I've push an update, please try again please (v1.1.0)

**Comment by alxbrla** [comment]
You forgot the peerDependencies (package.json - line 27), this throw a conflict for instalation

**Comment by cldt-fr** [comment]
Sorry for the mistake, i've push v1.1.1
